### PR TITLE
Update harbour-batterybuddy-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
Translation to Slovak

### CODE REVIEW

**Comment by okruhliak** [comment]
translation proofreading

**Comment by okruhliak** [comment]
Hi @direc85, thank you for the Slovak implementation, but it does not work in version 4.2.3-1, it is not active.

**Comment by okruhliak** [comment]
:+1:  thanks, it's okay now

**Comment by direc85** [comment]
Thanks for reporting!

**Pull request merged**
